# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='checklist',
            field=models.NullBooleanField(default='false'),
        ),
    ]
